### ISSUE TITLE
Any quick examples you can share?

### ISSUE THREAD

**Issue by ryanbuiltthat** [webantic/aws-s3-sts#1]
I've been trying to use this package to work with my S3 bucket. I use Slingshot for the uploads but anytime I try something else I get the following:

`Discarding entity body for GET requests`

Do you have any examples of how to use your package? Right now all I'm trying to do is list objects in a bucket.

**Comment by carlevans719** [comment]
To be honest, whenever we've needed to actually use the SDK directly, we've used the `peerlibrary:aws-sdk` package. We use this package when our only interaction between app --> AWS is uploading files to S3 and we don't want a bloated dependency.

If you're <1.3 I'd recommend just using the peerlibrary smart package, otherwise `import aws-sdk from 'aws-sdk';`

We have examples of using this package with Slingshot but it sounds like you're ok on that side - let me know if you'd find them useful though.

**Comment by ceuk** [comment]
Closing this due to age
